//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\della\projects\the-interpreter-101\Lang.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class LangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OE=1, CE=2, OB=3, CB=4, EQ=5, SUM=6, SUB=7, MUL=8, DIV=9, AND=10, OR=11, 
		RELOP_EQ=12, RELOP_NE=13, RELOP_LT=14, RELOP_LE=15, RELOP_GT=16, RELOP_GE=17, 
		BOOL_TRUE=18, BOL_FALSE=19, IF=20, THEN=21, ELSE=22, WRITE=23, READ=24, 
		STR=25, EOL=26, NUM=27, VAR=28, COMMENT=29, WS=30;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"OE", "CE", "OB", "CB", "EQ", "SUM", "SUB", "MUL", "DIV", "AND", "OR", 
		"RELOP_EQ", "RELOP_NE", "RELOP_LT", "RELOP_LE", "RELOP_GT", "RELOP_GE", 
		"BOOL_TRUE", "BOL_FALSE", "IF", "THEN", "ELSE", "WRITE", "READ", "STR", 
		"EOL", "NUM", "VAR", "COMMENT", "WS"
	};


	public LangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'{'", "'}'", "'='", "'+'", "'-'", "'*'", "'/'", "'&&'", 
		"'||'", "'=='", "'!='", "'<'", "'<='", "'>'", "'>='", "'true'", "'false'", 
		null, null, null, null, null, null, "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OE", "CE", "OB", "CB", "EQ", "SUM", "SUB", "MUL", "DIV", "AND", 
		"OR", "RELOP_EQ", "RELOP_NE", "RELOP_LT", "RELOP_LE", "RELOP_GT", "RELOP_GE", 
		"BOOL_TRUE", "BOL_FALSE", "IF", "THEN", "ELSE", "WRITE", "READ", "STR", 
		"EOL", "NUM", "VAR", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ' ', '\xB9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', 
		'\a', '\x1A', '\x8D', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\x90', 
		'\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1C', '\x6', '\x1C', '\x97', '\n', '\x1C', '\r', '\x1C', '\xE', 
		'\x1C', '\x98', '\x3', '\x1C', '\x3', '\x1C', '\x6', '\x1C', '\x9D', '\n', 
		'\x1C', '\r', '\x1C', '\xE', '\x1C', '\x9E', '\x5', '\x1C', '\xA1', '\n', 
		'\x1C', '\x3', '\x1D', '\x6', '\x1D', '\xA4', '\n', '\x1D', '\r', '\x1D', 
		'\xE', '\x1D', '\xA5', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\a', '\x1E', '\xAC', '\n', '\x1E', '\f', '\x1E', '\xE', '\x1E', 
		'\xAF', '\v', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x6', 
		'\x1F', '\xB4', '\n', '\x1F', '\r', '\x1F', '\xE', '\x1F', '\xB5', '\x3', 
		'\x1F', '\x3', '\x1F', '\x2', '\x2', ' ', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', 
		'\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', 
		'\x1E', ';', '\x1F', '=', ' ', '\x3', '\x2', '\x13', '\x4', '\x2', 'K', 
		'K', 'k', 'k', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', 'V', 'V', 
		'v', 'v', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', '\x2', 'G', 'G', 'g', 
		'g', '\x4', '\x2', 'P', 'P', 'p', 'p', '\x4', '\x2', 'N', 'N', 'n', 'n', 
		'\x4', '\x2', 'U', 'U', 'u', 'u', '\x4', '\x2', 'Y', 'Y', 'y', 'y', '\x4', 
		'\x2', 'T', 'T', 't', 't', '\x4', '\x2', '\x43', '\x43', '\x63', '\x63', 
		'\x4', '\x2', '\x46', '\x46', '\x66', '\x66', '\x3', '\x2', '$', '$', 
		'\x3', '\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x4', 
		'\x2', '\f', '\f', '\xF', '\xF', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x2', '\xBF', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'=', '\x3', '\x2', '\x2', '\x2', '\x3', '?', '\x3', '\x2', '\x2', '\x2', 
		'\x5', '\x41', '\x3', '\x2', '\x2', '\x2', '\a', '\x43', '\x3', '\x2', 
		'\x2', '\x2', '\t', '\x45', '\x3', '\x2', '\x2', '\x2', '\v', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\r', 'I', '\x3', '\x2', '\x2', '\x2', '\xF', 'K', 
		'\x3', '\x2', '\x2', '\x2', '\x11', 'M', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'O', '\x3', '\x2', '\x2', '\x2', '\x15', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'\x17', 'T', '\x3', '\x2', '\x2', '\x2', '\x19', 'W', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', 'Z', '\x3', '\x2', '\x2', '\x2', '\x1D', ']', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '_', '\x3', '\x2', '\x2', '\x2', '!', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '#', '\x64', '\x3', '\x2', '\x2', '\x2', '%', 'g', 
		'\x3', '\x2', '\x2', '\x2', '\'', 'l', '\x3', '\x2', '\x2', '\x2', ')', 
		'r', '\x3', '\x2', '\x2', '\x2', '+', 'u', '\x3', '\x2', '\x2', '\x2', 
		'-', 'z', '\x3', '\x2', '\x2', '\x2', '/', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x85', '\x3', '\x2', '\x2', '\x2', '\x33', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x93', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x39', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xA7', '\x3', '\x2', '\x2', '\x2', '=', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '?', '@', '\a', '*', '\x2', '\x2', '@', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\x42', '\a', '+', '\x2', '\x2', '\x42', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', '}', '\x2', '\x2', '\x44', 
		'\b', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x7F', '\x2', 
		'\x2', '\x46', '\n', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '?', 
		'\x2', '\x2', 'H', '\f', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', '-', 
		'\x2', '\x2', 'J', '\xE', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', 
		'/', '\x2', '\x2', 'L', '\x10', '\x3', '\x2', '\x2', '\x2', 'M', 'N', 
		'\a', ',', '\x2', '\x2', 'N', '\x12', '\x3', '\x2', '\x2', '\x2', 'O', 
		'P', '\a', '\x31', '\x2', '\x2', 'P', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '(', '\x2', '\x2', 'R', 'S', '\a', '(', '\x2', '\x2', 
		'S', '\x16', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', '~', '\x2', '\x2', 
		'U', 'V', '\a', '~', '\x2', '\x2', 'V', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\a', '?', '\x2', '\x2', 'X', 'Y', '\a', '?', '\x2', '\x2', 
		'Y', '\x1A', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '#', '\x2', '\x2', 
		'[', '\\', '\a', '?', '\x2', '\x2', '\\', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', ']', '^', '\a', '>', '\x2', '\x2', '^', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '_', '`', '\a', '>', '\x2', '\x2', '`', '\x61', '\a', '?', '\x2', 
		'\x2', '\x61', ' ', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', 
		'@', '\x2', '\x2', '\x63', '\"', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', 
		'\a', '@', '\x2', '\x2', '\x65', '\x66', '\a', '?', '\x2', '\x2', '\x66', 
		'$', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 'v', '\x2', '\x2', 'h', 
		'i', '\a', 't', '\x2', '\x2', 'i', 'j', '\a', 'w', '\x2', '\x2', 'j', 
		'k', '\a', 'g', '\x2', '\x2', 'k', '&', '\x3', '\x2', '\x2', '\x2', 'l', 
		'm', '\a', 'h', '\x2', '\x2', 'm', 'n', '\a', '\x63', '\x2', '\x2', 'n', 
		'o', '\a', 'n', '\x2', '\x2', 'o', 'p', '\a', 'u', '\x2', '\x2', 'p', 
		'q', '\a', 'g', '\x2', '\x2', 'q', '(', '\x3', '\x2', '\x2', '\x2', 'r', 
		's', '\t', '\x2', '\x2', '\x2', 's', 't', '\t', '\x3', '\x2', '\x2', 't', 
		'*', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\t', '\x4', '\x2', '\x2', 
		'v', 'w', '\t', '\x5', '\x2', '\x2', 'w', 'x', '\t', '\x6', '\x2', '\x2', 
		'x', 'y', '\t', '\a', '\x2', '\x2', 'y', ',', '\x3', '\x2', '\x2', '\x2', 
		'z', '{', '\t', '\x6', '\x2', '\x2', '{', '|', '\t', '\b', '\x2', '\x2', 
		'|', '}', '\t', '\t', '\x2', '\x2', '}', '~', '\t', '\x6', '\x2', '\x2', 
		'~', '.', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\t', '\n', '\x2', 
		'\x2', '\x80', '\x81', '\t', '\v', '\x2', '\x2', '\x81', '\x82', '\t', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\t', '\x4', '\x2', '\x2', '\x83', 
		'\x84', '\t', '\x6', '\x2', '\x2', '\x84', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\t', '\v', '\x2', '\x2', '\x86', '\x87', '\t', 
		'\x6', '\x2', '\x2', '\x87', '\x88', '\t', '\f', '\x2', '\x2', '\x88', 
		'\x89', '\t', '\r', '\x2', '\x2', '\x89', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8E', '\a', '$', '\x2', '\x2', '\x8B', '\x8D', '\n', 
		'\xE', '\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x92', '\a', '$', '\x2', '\x2', '\x92', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\a', '=', '\x2', '\x2', '\x94', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x97', '\t', '\xF', '\x2', '\x2', '\x96', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9C', '\v', '\x2', '\x2', '\x2', '\x9B', '\x9D', '\t', '\xF', '\x2', 
		'\x2', '\x9C', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\x38', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA4', '\t', '\x10', '\x2', '\x2', '\xA3', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		':', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\a', '\x31', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', '\x31', '\x2', '\x2', '\xA9', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xAC', '\n', '\x11', '\x2', '\x2', '\xAB', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\b', '\x1E', '\x2', 
		'\x2', '\xB1', '<', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB4', '\t', 
		'\x12', '\x2', '\x2', '\xB3', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xB8', '\b', '\x1F', '\x2', '\x2', '\xB8', 
		'>', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', '\x8E', '\x98', '\x9E', 
		'\xA0', '\xA5', '\xAD', '\xB5', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Grammar
