//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\della\projects\the-interpreter-101\Lang.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ILangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] LangParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] LangParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] LangParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] LangParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] LangParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] LangParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput([NotNull] LangParser.InputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput([NotNull] LangParser.InputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput([NotNull] LangParser.OutputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput([NotNull] LangParser.OutputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.ifst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfst([NotNull] LangParser.IfstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.ifst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfst([NotNull] LangParser.IfstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LangParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LangParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCond([NotNull] LangParser.CondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCond([NotNull] LangParser.CondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelop([NotNull] LangParser.RelopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelop([NotNull] LangParser.RelopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtrib([NotNull] LangParser.AtribContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtrib([NotNull] LangParser.AtribContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] LangParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] LangParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] LangParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] LangParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] LangParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] LangParser.FactorContext context);
}
} // namespace Grammar
