//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\della\projects\the-interpreter-101\Lang.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class LangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OE=1, CE=2, OB=3, CB=4, EQ=5, PLUS=6, MINUS=7, MULT=8, DIV=9, AND=10, 
		OR=11, RELOP=12, BOOL_TRUE=13, BOL_FALSE=14, IF=15, THEN=16, ELSE=17, 
		WRITE=18, READ=19, STR=20, EOL=21, NUM=22, VAR=23, COMMENT=24, WS=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"OE", "CE", "OB", "CB", "EQ", "PLUS", "MINUS", "MULT", "DIV", "AND", "OR", 
		"RELOP", "BOOL_TRUE", "BOL_FALSE", "IF", "THEN", "ELSE", "WRITE", "READ", 
		"STR", "EOL", "NUM", "VAR", "COMMENT", "WS"
	};


	public LangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'{'", "'}'", "'='", "'+'", "'-'", "'*'", "'/'", "'&&'", 
		"'||'", null, "'true'", "'false'", null, null, null, null, null, null, 
		"';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OE", "CE", "OB", "CB", "EQ", "PLUS", "MINUS", "MULT", "DIV", "AND", 
		"OR", "RELOP", "BOOL_TRUE", "BOL_FALSE", "IF", "THEN", "ELSE", "WRITE", 
		"READ", "STR", "EOL", "NUM", "VAR", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xAB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x5', '\r', 'X', '\n', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\a', '\x15', '\x7F', '\n', '\x15', '\f', '\x15', '\xE', '\x15', 
		'\x82', '\v', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x6', '\x17', '\x89', '\n', '\x17', '\r', '\x17', 
		'\xE', '\x17', '\x8A', '\x3', '\x17', '\x3', '\x17', '\x6', '\x17', '\x8F', 
		'\n', '\x17', '\r', '\x17', '\xE', '\x17', '\x90', '\x5', '\x17', '\x93', 
		'\n', '\x17', '\x3', '\x18', '\x6', '\x18', '\x96', '\n', '\x18', '\r', 
		'\x18', '\xE', '\x18', '\x97', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\a', '\x19', '\x9E', '\n', '\x19', '\f', '\x19', '\xE', 
		'\x19', '\xA1', '\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x6', '\x1A', '\xA6', '\n', '\x1A', '\r', '\x1A', '\xE', '\x1A', '\xA7', 
		'\x3', '\x1A', '\x3', '\x1A', '\x2', '\x2', '\x1B', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', 
		'\x19', '\x31', '\x1A', '\x33', '\x1B', '\x3', '\x2', '\x13', '\x4', '\x2', 
		'K', 'K', 'k', 'k', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', 'V', 
		'V', 'v', 'v', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', '\x2', 'G', 'G', 
		'g', 'g', '\x4', '\x2', 'P', 'P', 'p', 'p', '\x4', '\x2', 'N', 'N', 'n', 
		'n', '\x4', '\x2', 'U', 'U', 'u', 'u', '\x4', '\x2', 'Y', 'Y', 'y', 'y', 
		'\x4', '\x2', 'T', 'T', 't', 't', '\x4', '\x2', '\x43', '\x43', '\x63', 
		'\x63', '\x4', '\x2', '\x46', '\x46', '\x66', '\x66', '\x3', '\x2', '$', 
		'$', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x5', '\x2', '\v', '\f', '\xF', 
		'\xF', '\"', '\"', '\x2', '\xB6', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x3', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x37', '\x3', '\x2', '\x2', '\x2', '\a', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\t', ';', '\x3', '\x2', '\x2', '\x2', '\v', 
		'=', '\x3', '\x2', '\x2', '\x2', '\r', '?', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x41', '\x3', '\x2', '\x2', '\x2', '\x11', '\x43', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x45', '\x3', '\x2', '\x2', '\x2', '\x15', 'G', 
		'\x3', '\x2', '\x2', '\x2', '\x17', 'J', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'W', '\x3', '\x2', '\x2', '\x2', '\x1B', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '^', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '!', 'g', '\x3', '\x2', '\x2', '\x2', '#', 'l', '\x3', '\x2', 
		'\x2', '\x2', '%', 'q', '\x3', '\x2', '\x2', '\x2', '\'', 'w', '\x3', 
		'\x2', '\x2', '\x2', ')', '|', '\x3', '\x2', '\x2', '\x2', '+', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '-', '\x88', '\x3', '\x2', '\x2', '\x2', '/', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x31', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xA5', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 
		'*', '\x2', '\x2', '\x36', '\x4', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\a', '+', '\x2', '\x2', '\x38', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\a', '}', '\x2', '\x2', ':', '\b', '\x3', '\x2', '\x2', 
		'\x2', ';', '<', '\a', '\x7F', '\x2', '\x2', '<', '\n', '\x3', '\x2', 
		'\x2', '\x2', '=', '>', '\a', '?', '\x2', '\x2', '>', '\f', '\x3', '\x2', 
		'\x2', '\x2', '?', '@', '\a', '-', '\x2', '\x2', '@', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\x42', '\a', '/', '\x2', '\x2', '\x42', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', ',', '\x2', '\x2', '\x44', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x31', '\x2', 
		'\x2', '\x46', '\x14', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '(', 
		'\x2', '\x2', 'H', 'I', '\a', '(', '\x2', '\x2', 'I', '\x16', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'K', '\a', '~', '\x2', '\x2', 'K', 'L', '\a', '~', 
		'\x2', '\x2', 'L', '\x18', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 
		'?', '\x2', '\x2', 'N', 'X', '\a', '?', '\x2', '\x2', 'O', 'P', '\a', 
		'#', '\x2', '\x2', 'P', 'X', '\a', '?', '\x2', '\x2', 'Q', 'X', '\a', 
		'>', '\x2', '\x2', 'R', 'S', '\a', '>', '\x2', '\x2', 'S', 'X', '\a', 
		'?', '\x2', '\x2', 'T', 'X', '\a', '@', '\x2', '\x2', 'U', 'V', '\a', 
		'@', '\x2', '\x2', 'V', 'X', '\a', '?', '\x2', '\x2', 'W', 'M', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'O', '\x3', '\x2', '\x2', '\x2', 'W', 'Q', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'R', '\x3', '\x2', '\x2', '\x2', 'W', 'T', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 'X', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', 'v', '\x2', '\x2', 'Z', '[', 
		'\a', 't', '\x2', '\x2', '[', '\\', '\a', 'w', '\x2', '\x2', '\\', ']', 
		'\a', 'g', '\x2', '\x2', ']', '\x1C', '\x3', '\x2', '\x2', '\x2', '^', 
		'_', '\a', 'h', '\x2', '\x2', '_', '`', '\a', '\x63', '\x2', '\x2', '`', 
		'\x61', '\a', 'n', '\x2', '\x2', '\x61', '\x62', '\a', 'u', '\x2', '\x2', 
		'\x62', '\x63', '\a', 'g', '\x2', '\x2', '\x63', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\t', '\x2', '\x2', '\x2', '\x65', '\x66', 
		'\t', '\x3', '\x2', '\x2', '\x66', ' ', '\x3', '\x2', '\x2', '\x2', 'g', 
		'h', '\t', '\x4', '\x2', '\x2', 'h', 'i', '\t', '\x5', '\x2', '\x2', 'i', 
		'j', '\t', '\x6', '\x2', '\x2', 'j', 'k', '\t', '\a', '\x2', '\x2', 'k', 
		'\"', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\t', '\x6', '\x2', '\x2', 
		'm', 'n', '\t', '\b', '\x2', '\x2', 'n', 'o', '\t', '\t', '\x2', '\x2', 
		'o', 'p', '\t', '\x6', '\x2', '\x2', 'p', '$', '\x3', '\x2', '\x2', '\x2', 
		'q', 'r', '\t', '\n', '\x2', '\x2', 'r', 's', '\t', '\v', '\x2', '\x2', 
		's', 't', '\t', '\x2', '\x2', '\x2', 't', 'u', '\t', '\x4', '\x2', '\x2', 
		'u', 'v', '\t', '\x6', '\x2', '\x2', 'v', '&', '\x3', '\x2', '\x2', '\x2', 
		'w', 'x', '\t', '\v', '\x2', '\x2', 'x', 'y', '\t', '\x6', '\x2', '\x2', 
		'y', 'z', '\t', '\f', '\x2', '\x2', 'z', '{', '\t', '\r', '\x2', '\x2', 
		'{', '(', '\x3', '\x2', '\x2', '\x2', '|', '\x80', '\a', '$', '\x2', '\x2', 
		'}', '\x7F', '\n', '\xE', '\x2', '\x2', '~', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x82', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x84', '\a', '$', '\x2', '\x2', '\x84', '*', '\x3', '\x2', 
		'\x2', '\x2', '\x85', '\x86', '\a', '=', '\x2', '\x2', '\x86', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x89', '\t', '\xF', '\x2', '\x2', '\x88', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x92', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8E', '\v', '\x2', '\x2', '\x2', '\x8D', '\x8F', '\t', '\xF', '\x2', 
		'\x2', '\x8E', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '.', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x96', '\t', '\x10', '\x2', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\x31', '\x2', 
		'\x2', '\x9A', '\x9B', '\a', '\x31', '\x2', '\x2', '\x9B', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\n', '\x11', '\x2', '\x2', '\x9D', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\b', '\x19', '\x2', 
		'\x2', '\xA3', '\x32', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA6', '\t', 
		'\x12', '\x2', '\x2', '\xA5', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xAA', '\b', '\x1A', '\x2', '\x2', '\xAA', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', 'W', '\x80', '\x8A', 
		'\x90', '\x92', '\x97', '\x9F', '\xA7', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Grammar
